spring.application.name=denguard-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/denguard
spring.datasource.username=denguard
spring.datasource.password=denguard

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080